"""Resident-facing text about the six steps, in all six languages: next actions, what LifeLoop and the parent do,
expected timings, fee notes, consulate milestones and the legal-deadline source.

English comes from the workflow template (the single source); a missing translation falls back to English.
"""
from __future__ import annotations

from app.core.i18n import normalise_lang
from app.workflows.birth_expat import TEMPLATE

EN: dict[str, str] = {
    "next_after": "Starts after {steps}",
    "next_waiting": "Waiting for an earlier step",
    "next_ready": "LifeLoop is preparing the filing",
    "next_officer": "An Amer officer must release this submission",
    "next_with": "With {entity} - LifeLoop will call when it changes",
    "next_provide": "Provide: {doc}",
    "next_missing_doc": "the missing document",
    "next_blocked": "An officer is reviewing the hold",
    "next_stalled": "Not cleared yet - an officer is following up",
    "next_rejected": "An officer is reviewing the authority's decision",
    "next_consulate": "Attend the consulate and tell LifeLoop when the passport is issued",
    "next_biometrics": "Attend ICP biometrics with the child",
    "entity_CONSULATE": "the consulate",
    "entity_INSURER": "the insurer",
    "milestone_APPOINTMENT_BOOKED": "Consulate appointment booked",
    "milestone_APPLICATION_SUBMITTED": "Passport application submitted at the consulate",
    "milestone_PASSPORT_ISSUED": "Passport issued",
    "milestone_DELAYED": "Parent reports no progress at the consulate",
    "deadline_source": "Idea Canvas box C: 120-day legal deadline for the newborn residence process",
}
for _tpl in TEMPLATE:
    EN[f"does_{_tpl.key}"] = _tpl.lifeloop_does
    EN[f"parent_{_tpl.key}"] = _tpl.parent_does
    EN[f"sla_{_tpl.key}"] = _tpl.sla_label
    if _tpl.resident_present_reason:
        EN[f"present_{_tpl.key}"] = _tpl.resident_present_reason
    if _tpl.fee_note:
        EN[f"fee_{_tpl.key}"] = _tpl.fee_note

_PASSPORT_ML = "പാസ്‌പോർട്ട്"

TRANSLATIONS: dict[str, dict[str, str]] = {
    "ar": {
        "next_after": "تبدأ بعد {steps}",
        "next_waiting": "بانتظار خطوة سابقة",
        "next_ready": "يُعِدّ LifeLoop الطلب الآن",
        "next_officer": "يجب أن يُجيز موظف في Amer هذا الطلب قبل إرساله",
        "next_with": "لدى {entity} - سيتصل بك LifeLoop عند حدوث أي تغيير",
        "next_provide": "يُرجى تقديم: {doc}",
        "next_missing_doc": "المستند الناقص",
        "next_blocked": "يراجع موظف سبب التوقف",
        "next_stalled": "لم تُنجَز بعد - يتابعها موظف",
        "next_rejected": "يراجع موظف قرار الجهة المختصة",
        "next_consulate": "راجِع القنصلية وأبلِغ LifeLoop عند إصدار الجواز",
        "next_biometrics": "احضر مع الطفل لأخذ البصمات لدى ICP",
        "entity_CONSULATE": "القنصلية",
        "entity_INSURER": "شركة التأمين",
        "present_CONSULATE_PASSPORT": "موعد القنصلية",
        "present_EMIRATES_ID": "أخذ البصمات لدى ICP",
        "does_BIRTH_CERTIFICATE": "يُعِدّ الطلب ويقدّمه إلى الجهة المُصدِرة في إمارتك بعد أن يُجيزه موظف.",
        "parent_BIRTH_CERTIFICATE": "لا يلزمك الحضور. يجب أن تكون شهادة الزواج المصدّقة جاهزة قبل بدء هذه الخطوة.",
        "does_MOFA_ATTESTATION": "يقدّم طلب التصديق إلى وزارة الخارجية MOFA بعد أن يُجيزه موظف.",
        "parent_MOFA_ATTESTATION": "لا يلزمك الحضور.",
        "does_CONSULATE_PASSPORT": "لا يستطيع تقديم هذه الخطوة أو تتبّعها: لا توفّر القنصلية واجهة برمجية ولا مدة خدمة معلنة ولا تحديثات للحالة. "
                                   "يسألك LifeLoop عن كل مرحلة ويسجّلها على أنها أبلغ عنها ولي الأمر.",
        "parent_CONSULATE_PASSPORT": "احجز موعد القنصلية واحضره، ثم أبلِغ LifeLoop عند إصدار الجواز.",
        "does_RESIDENCE_VISA": "يعيد تخطيط طلب التأشيرة فور الإبلاغ عن الجواز، ثم يقدّمه بعد أن يُجيزه موظف.",
        "parent_RESIDENCE_VISA": "لا يلزمك الحضور ما لم تطلب الجهة المختصة مستندًا.",
        "does_EMIRATES_ID": "يقدّم طلب الهوية الإماراتية بعد أن يُجيزه موظف، ويُعلمك بموعد أخذ البصمات.",
        "parent_EMIRATES_ID": "احضر مع الطفل لأخذ البصمات لدى ICP إذا طلب المركز ذلك.",
        "does_INSURANCE": "يقدّم طلب إضافة التابع إلى شركة التأمين عبر منصة DHA eClaimLink بعد أن يُجيزه موظف.",
        "parent_INSURANCE": "لا يلزمك الحضور.",
        "sla_BIRTH_CERTIFICATE": "من 1 إلى 5 أيام",
        "sla_MOFA_ATTESTATION": "من ساعتين إلى 3 أيام عمل",
        "sla_CONSULATE_PASSPORT": "لا توجد مدة معلنة - من أسبوعين إلى 8 أسابيع دون تحديثات للحالة",
        "sla_RESIDENCE_VISA": "من 3 إلى 10 أيام، وتبقى متوقفة حتى تُنجَز خطوة القنصلية",
        "sla_EMIRATES_ID": "من 5 إلى 15 يومًا، وتصل البطاقة عبر البريد السريع",
        "sla_INSURANCE": "مدة مستهدفة من LifeLoop (لا توجد مدة معلنة في مصادرنا)",
        "fee_MOFA_ATTESTATION": "رسوم تصديق 150 درهمًا (Idea Canvas، الخانة H، المرحلة 3؛ يُرجى التأكد من جدول رسوم MOFA الحالي)",
        "milestone_APPOINTMENT_BOOKED": "تم حجز موعد القنصلية",
        "milestone_APPLICATION_SUBMITTED": "تم تقديم طلب الجواز في القنصلية",
        "milestone_PASSPORT_ISSUED": "صدر الجواز",
        "milestone_DELAYED": "أبلغ ولي الأمر بعدم وجود تقدّم في القنصلية",
        "deadline_source": "Idea Canvas، الخانة C: مهلة قانونية مدتها 120 يومًا لإجراءات إقامة المولود",
    },
    "hi": {
        "next_after": "{steps} के बाद शुरू होगा",
        "next_waiting": "पिछले चरण का इंतज़ार",
        "next_ready": "LifeLoop आवेदन तैयार कर रहा है",
        "next_officer": "Amer के एक अधिकारी को यह आवेदन रिलीज़ करना है",
        "next_with": "{entity} के पास - कुछ बदलते ही LifeLoop आपको कॉल करेगा",
        "next_provide": "जमा करें: {doc}",
        "next_missing_doc": "छूटा हुआ दस्तावेज़",
        "next_blocked": "एक अधिकारी रुकावट की जाँच कर रहा है",
        "next_stalled": "अभी क्लियर नहीं हुआ - एक अधिकारी फ़ॉलो-अप कर रहा है",
        "next_rejected": "एक अधिकारी विभाग के फ़ैसले की समीक्षा कर रहा है",
        "next_consulate": "कॉन्सुलेट जाएँ और पासपोर्ट जारी होने पर LifeLoop को बताएँ",
        "next_biometrics": "बच्चे के साथ ICP बायोमेट्रिक्स के लिए जाएँ",
        "entity_CONSULATE": "कॉन्सुलेट",
        "entity_INSURER": "बीमा कंपनी",
        "present_CONSULATE_PASSPORT": "कॉन्सुलेट अपॉइंटमेंट",
        "present_EMIRATES_ID": "ICP बायोमेट्रिक्स",
        "does_BIRTH_CERTIFICATE": "अधिकारी के रिलीज़ करने के बाद आपके अमीरात के जारीकर्ता विभाग के पास आवेदन तैयार करके दाख़िल करता है।",
        "parent_BIRTH_CERTIFICATE": "कहीं जाने की ज़रूरत नहीं। यह चरण शुरू होने से पहले सत्यापित विवाह प्रमाण पत्र तैयार होना चाहिए।",
        "does_MOFA_ATTESTATION": "अधिकारी के रिलीज़ करने के बाद MOFA के पास सत्यापन का अनुरोध दाख़िल करता है।",
        "parent_MOFA_ATTESTATION": "कहीं जाने की ज़रूरत नहीं।",
        "does_CONSULATE_PASSPORT": "यह चरण न दाख़िल कर सकता है, न ट्रैक कर सकता है: कॉन्सुलेट के पास कोई API, कोई SLA और कोई स्टेटस फ़ीड नहीं है। "
                                   "LifeLoop हर पड़ाव के बारे में आपसे पूछता है और उसे माता-पिता की दी हुई जानकारी के रूप में दर्ज करता है।",
        "parent_CONSULATE_PASSPORT": "कॉन्सुलेट की अपॉइंटमेंट बुक करें और वहाँ जाएँ, फिर पासपोर्ट जारी होने पर LifeLoop को बताएँ।",
        "does_RESIDENCE_VISA": "पासपोर्ट की सूचना मिलते ही वीज़ा आवेदन की योजना दोबारा बनाता है, फिर अधिकारी के रिलीज़ करने के बाद दाख़िल करता है।",
        "parent_RESIDENCE_VISA": "कहीं जाने की ज़रूरत नहीं, जब तक विभाग कोई दस्तावेज़ न माँगे।",
        "does_EMIRATES_ID": "अधिकारी के रिलीज़ करने के बाद एमिरेट्स आईडी का आवेदन दाख़िल करता है और बायोमेट्रिक्स का समय आने पर आपको बताता है।",
        "parent_EMIRATES_ID": "अगर सेंटर कहे तो बच्चे के साथ ICP बायोमेट्रिक्स के लिए जाएँ।",
        "does_INSURANCE": "अधिकारी के रिलीज़ करने के बाद DHA eClaimLink के ज़रिए बीमा कंपनी के पास आश्रित को जोड़ने का आवेदन दाख़िल करता है।",
        "parent_INSURANCE": "कहीं जाने की ज़रूरत नहीं।",
        "sla_BIRTH_CERTIFICATE": "1-5 दिन",
        "sla_MOFA_ATTESTATION": "2 घंटे से 3 कार्य दिवस",
        "sla_CONSULATE_PASSPORT": "कोई SLA नहीं - 2 से 8 हफ़्ते, कोई स्टेटस फ़ीड नहीं",
        "sla_RESIDENCE_VISA": "3-10 दिन, कॉन्सुलेट वाला चरण पूरा होने तक रुका रहता है",
        "sla_EMIRATES_ID": "5-15 दिन, कार्ड कूरियर से आता है",
        "sla_INSURANCE": "LifeLoop का सेवा लक्ष्य (हमारे स्रोतों में कोई प्रकाशित SLA नहीं)",
        "fee_MOFA_ATTESTATION": "AED 150 सत्यापन शुल्क (Idea Canvas बॉक्स H, चरण 3; MOFA की मौजूदा शुल्क सूची से पुष्टि करें)",
        "milestone_APPOINTMENT_BOOKED": "कॉन्सुलेट अपॉइंटमेंट बुक हो गई",
        "milestone_APPLICATION_SUBMITTED": "कॉन्सुलेट में पासपोर्ट आवेदन जमा हो गया",
        "milestone_PASSPORT_ISSUED": "पासपोर्ट जारी हो गया",
        "milestone_DELAYED": "माता-पिता के अनुसार कॉन्सुलेट में कोई प्रगति नहीं",
        "deadline_source": "Idea Canvas बॉक्स C: नवजात की रेज़िडेंस प्रक्रिया के लिए 120 दिन की कानूनी समय सीमा",
    },
    "ur": {
        "next_after": "{steps} کے بعد شروع ہوگا",
        "next_waiting": "پچھلے مرحلے کا انتظار ہے",
        "next_ready": "LifeLoop درخواست تیار کر رہا ہے",
        "next_officer": "Amer کے ایک افسر کو یہ درخواست جاری کرنی ہے",
        "next_with": "{entity} کے پاس - کچھ بدلتے ہی LifeLoop آپ کو کال کرے گا",
        "next_provide": "فراہم کریں: {doc}",
        "next_missing_doc": "رہ جانے والی دستاویز",
        "next_blocked": "ایک افسر رکاوٹ کا جائزہ لے رہا ہے",
        "next_stalled": "ابھی کلیئر نہیں ہوا - ایک افسر پیروی کر رہا ہے",
        "next_rejected": "ایک افسر متعلقہ ادارے کے فیصلے کا جائزہ لے رہا ہے",
        "next_consulate": "قونصل خانے جائیں اور پاسپورٹ جاری ہونے پر LifeLoop کو بتائیں",
        "next_biometrics": "بچے کے ساتھ ICP بایومیٹرکس کے لیے جائیں",
        "entity_CONSULATE": "قونصل خانہ",
        "entity_INSURER": "انشورنس کمپنی",
        "present_CONSULATE_PASSPORT": "قونصل خانے کی اپائنٹمنٹ",
        "present_EMIRATES_ID": "ICP بایومیٹرکس",
        "does_BIRTH_CERTIFICATE": "افسر کے جاری کرنے کے بعد آپ کی امارت کے متعلقہ ادارے کے پاس درخواست تیار کر کے جمع کراتا ہے۔",
        "parent_BIRTH_CERTIFICATE": "کہیں جانے کی ضرورت نہیں۔ یہ مرحلہ شروع ہونے سے پہلے تصدیق شدہ نکاح نامہ تیار ہونا چاہیے۔",
        "does_MOFA_ATTESTATION": "افسر کے جاری کرنے کے بعد MOFA کے پاس تصدیق کی درخواست جمع کراتا ہے۔",
        "parent_MOFA_ATTESTATION": "کہیں جانے کی ضرورت نہیں۔",
        "does_CONSULATE_PASSPORT": "یہ مرحلہ نہ جمع کرا سکتا ہے نہ ٹریک کر سکتا ہے: قونصل خانے کے پاس نہ کوئی API ہے، نہ SLA اور نہ اسٹیٹس فیڈ۔ "
                                   "LifeLoop ہر مرحلے کے بارے میں آپ سے پوچھتا ہے اور اسے والدین کی دی ہوئی اطلاع کے طور پر درج کرتا ہے۔",
        "parent_CONSULATE_PASSPORT": "قونصل خانے کی اپائنٹمنٹ بک کریں اور وہاں جائیں، پھر پاسپورٹ جاری ہونے پر LifeLoop کو بتائیں۔",
        "does_RESIDENCE_VISA": "پاسپورٹ کی اطلاع ملتے ہی ویزا درخواست کی منصوبہ بندی دوبارہ کرتا ہے، پھر افسر کے جاری کرنے کے بعد جمع کراتا ہے۔",
        "parent_RESIDENCE_VISA": "کہیں جانے کی ضرورت نہیں، جب تک متعلقہ ادارہ کوئی دستاویز نہ مانگے۔",
        "does_EMIRATES_ID": "افسر کے جاری کرنے کے بعد امارات آئی ڈی کی درخواست جمع کراتا ہے اور بایومیٹرکس کا وقت آنے پر آپ کو بتاتا ہے۔",
        "parent_EMIRATES_ID": "اگر مرکز کہے تو بچے کے ساتھ ICP بایومیٹرکس کے لیے جائیں۔",
        "does_INSURANCE": "افسر کے جاری کرنے کے بعد DHA eClaimLink کے ذریعے انشورنس کمپنی کے پاس زیرِ کفالت فرد کے اندراج کی درخواست جمع کراتا ہے۔",
        "parent_INSURANCE": "کہیں جانے کی ضرورت نہیں۔",
        "sla_BIRTH_CERTIFICATE": "1 سے 5 دن",
        "sla_MOFA_ATTESTATION": "2 گھنٹے سے 3 کاروباری دن",
        "sla_CONSULATE_PASSPORT": "کوئی SLA نہیں - 2 سے 8 ہفتے، کوئی اسٹیٹس فیڈ نہیں",
        "sla_RESIDENCE_VISA": "3 سے 10 دن، قونصل خانے کا مرحلہ مکمل ہونے تک رکا رہتا ہے",
        "sla_EMIRATES_ID": "5 سے 15 دن، کارڈ کوریئر سے آتا ہے",
        "sla_INSURANCE": "LifeLoop کا سروس ہدف (ہمارے ذرائع میں کوئی شائع شدہ SLA نہیں)",
        "fee_MOFA_ATTESTATION": "AED 150 تصدیقی فیس (Idea Canvas خانہ H، مرحلہ 3؛ MOFA کی موجودہ فیس فہرست سے تصدیق کریں)",
        "milestone_APPOINTMENT_BOOKED": "قونصل خانے کی اپائنٹمنٹ بک ہو گئی",
        "milestone_APPLICATION_SUBMITTED": "قونصل خانے میں پاسپورٹ کی درخواست جمع ہو گئی",
        "milestone_PASSPORT_ISSUED": "پاسپورٹ جاری ہو گیا",
        "milestone_DELAYED": "والدین کے مطابق قونصل خانے میں کوئی پیش رفت نہیں",
        "deadline_source": "Idea Canvas خانہ C: نوزائیدہ کی رہائش کے عمل کے لیے 120 دن کی قانونی مہلت",
    },
    "ml": {
        "next_after": "{steps} കഴിഞ്ഞ് ആരംഭിക്കും",
        "next_waiting": "മുമ്പത്തെ ഘട്ടത്തിനായി കാത്തിരിക്കുന്നു",
        "next_ready": "LifeLoop അപേക്ഷ തയ്യാറാക്കുന്നു",
        "next_officer": "ഒരു Amer ഉദ്യോഗസ്ഥൻ ഈ അപേക്ഷ റിലീസ് ചെയ്യണം",
        "next_with": "{entity} കൈകാര്യം ചെയ്യുന്നു - മാറ്റമുണ്ടാകുമ്പോൾ LifeLoop വിളിക്കും",
        "next_provide": "നൽകുക: {doc}",
        "next_missing_doc": "കുറവുള്ള രേഖ",
        "next_blocked": "ഒരു ഉദ്യോഗസ്ഥൻ തടസ്സം പരിശോധിക്കുന്നു",
        "next_stalled": "ഇതുവരെ ക്ലിയർ ആയിട്ടില്ല - ഒരു ഉദ്യോഗസ്ഥൻ പിന്തുടരുന്നു",
        "next_rejected": "വകുപ്പിന്റെ തീരുമാനം ഒരു ഉദ്യോഗസ്ഥൻ പരിശോധിക്കുന്നു",
        "next_consulate": f"കോൺസുലേറ്റിൽ പോകുക, {_PASSPORT_ML} ഇഷ്യൂ ചെയ്താൽ LifeLoop-നെ അറിയിക്കുക",
        "next_biometrics": "കുട്ടിയുമായി ICP ബയോമെട്രിക്സിന് പോകുക",
        "entity_CONSULATE": "കോൺസുലേറ്റ്",
        "entity_INSURER": "ഇൻഷുറൻസ് കമ്പനി",
        "present_CONSULATE_PASSPORT": "കോൺസുലേറ്റ് അപ്പോയിന്റ്മെന്റ്",
        "present_EMIRATES_ID": "ICP ബയോമെട്രിക്സ്",
        "does_BIRTH_CERTIFICATE": "ഒരു ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്തശേഷം, നിങ്ങളുടെ എമിറേറ്റിലെ ബന്ധപ്പെട്ട വകുപ്പിൽ അപേക്ഷ തയ്യാറാക്കി ഫയൽ ചെയ്യുന്നു.",
        "parent_BIRTH_CERTIFICATE": "എവിടെയും പോകേണ്ടതില്ല. ഈ ഘട്ടം തുടങ്ങുന്നതിന് മുമ്പ് സാക്ഷ്യപ്പെടുത്തിയ വിവാഹ സർട്ടിഫിക്കറ്റ് തയ്യാറായിരിക്കണം.",
        "does_MOFA_ATTESTATION": "ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്തശേഷം MOFA-യിൽ സാക്ഷ്യപ്പെടുത്തൽ അപേക്ഷ ഫയൽ ചെയ്യുന്നു.",
        "parent_MOFA_ATTESTATION": "എവിടെയും പോകേണ്ടതില്ല.",
        "does_CONSULATE_PASSPORT": "ഈ ഘട്ടം ഫയൽ ചെയ്യാനോ ട്രാക്ക് ചെയ്യാനോ കഴിയില്ല: കോൺസുലേറ്റിന് API-യോ SLA-യോ സ്റ്റാറ്റസ് ഫീഡോ ഇല്ല. "
                                   "ഓരോ ഘട്ടവും LifeLoop നിങ്ങളോട് ചോദിച്ച് 'രക്ഷിതാവ് അറിയിച്ചത്' എന്ന നിലയിൽ രേഖപ്പെടുത്തുന്നു.",
        "parent_CONSULATE_PASSPORT": f"കോൺസുലേറ്റ് അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്ത് പോകുക, പിന്നെ {_PASSPORT_ML} ഇഷ്യൂ ചെയ്താൽ LifeLoop-നെ അറിയിക്കുക.",
        "does_RESIDENCE_VISA": f"{_PASSPORT_ML} അറിയിച്ചാലുടൻ വിസ അപേക്ഷ വീണ്ടും ആസൂത്രണം ചെയ്യുന്നു, തുടർന്ന് ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്തശേഷം ഫയൽ ചെയ്യുന്നു.",
        "parent_RESIDENCE_VISA": "വകുപ്പ് ഒരു രേഖ ആവശ്യപ്പെട്ടില്ലെങ്കിൽ എവിടെയും പോകേണ്ടതില്ല.",
        "does_EMIRATES_ID": "ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്തശേഷം എമിറേറ്റ്സ് ഐഡി അപേക്ഷ ഫയൽ ചെയ്യുന്നു, ബയോമെട്രിക്സ് സമയമാകുമ്പോൾ നിങ്ങളെ അറിയിക്കുന്നു.",
        "parent_EMIRATES_ID": "സെന്റർ ആവശ്യപ്പെട്ടാൽ കുട്ടിയുമായി ICP ബയോമെട്രിക്സിന് പോകുക.",
        "does_INSURANCE": "ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്തശേഷം DHA eClaimLink വഴി ഇൻഷുറൻസ് കമ്പനിയിൽ ആശ്രിതനെ ചേർക്കാനുള്ള അപേക്ഷ ഫയൽ ചെയ്യുന്നു.",
        "parent_INSURANCE": "എവിടെയും പോകേണ്ടതില്ല.",
        "sla_BIRTH_CERTIFICATE": "1-5 ദിവസം",
        "sla_MOFA_ATTESTATION": "2 മണിക്കൂർ - 3 പ്രവൃത്തി ദിവസം",
        "sla_CONSULATE_PASSPORT": "SLA ഇല്ല - 2 മുതൽ 8 ആഴ്ച വരെ, സ്റ്റാറ്റസ് ഫീഡ് ഇല്ല",
        "sla_RESIDENCE_VISA": "3-10 ദിവസം, കോൺസുലേറ്റ് ഘട്ടം പൂർത്തിയാകുന്നതുവരെ തടഞ്ഞിരിക്കും",
        "sla_EMIRATES_ID": "5-15 ദിവസം, കാർഡ് കൊറിയർ വഴി",
        "sla_INSURANCE": "LifeLoop സേവന ലക്ഷ്യം (ഞങ്ങളുടെ ഉറവിടങ്ങളിൽ പ്രസിദ്ധീകരിച്ച SLA ഇല്ല)",
        "fee_MOFA_ATTESTATION": "AED 150 സാക്ഷ്യപ്പെടുത്തൽ ഫീസ് (Idea Canvas ബോക്സ് H, ഘട്ടം 3; നിലവിലെ MOFA ഫീസ് പട്ടികയുമായി ഒത്തുനോക്കുക)",
        "milestone_APPOINTMENT_BOOKED": "കോൺസുലേറ്റ് അപ്പോയിന്റ്മെന്റ് ബുക്ക് ചെയ്തു",
        "milestone_APPLICATION_SUBMITTED": f"കോൺസുലേറ്റിൽ {_PASSPORT_ML} അപേക്ഷ നൽകി",
        "milestone_PASSPORT_ISSUED": f"{_PASSPORT_ML} ഇഷ്യൂ ചെയ്തു",
        "milestone_DELAYED": "കോൺസുലേറ്റിൽ പുരോഗതിയില്ലെന്ന് രക്ഷിതാവ് അറിയിച്ചു",
        "deadline_source": "Idea Canvas ബോക്സ് C: നവജാതശിശുവിന്റെ റെസിഡൻസ് നടപടിക്കുള്ള 120 ദിവസത്തെ നിയമപരമായ സമയപരിധി",
    },
    "tl": {
        "next_after": "Magsisimula pagkatapos ng {steps}",
        "next_waiting": "Naghihintay sa naunang hakbang",
        "next_ready": "Inihahanda ng LifeLoop ang filing",
        "next_officer": "Kailangang i-release ng isang Amer officer ang submission na ito",
        "next_with": "Nasa {entity} - tatawag ang LifeLoop kapag may pagbabago",
        "next_provide": "Ibigay: {doc}",
        "next_missing_doc": "ang kulang na dokumento",
        "next_blocked": "Sinusuri ng isang officer ang pagkaka-hold",
        "next_stalled": "Hindi pa cleared - may officer na nagfa-follow up",
        "next_rejected": "Sinusuri ng isang officer ang desisyon ng ahensya",
        "next_consulate": "Pumunta sa konsulado at sabihan ang LifeLoop kapag nailabas na ang passport",
        "next_biometrics": "Pumunta sa ICP biometrics kasama ang bata",
        "entity_CONSULATE": "konsulado",
        "entity_INSURER": "insurer",
        "present_CONSULATE_PASSPORT": "Appointment sa konsulado",
        "present_EMIRATES_ID": "ICP biometrics",
        "does_BIRTH_CERTIFICATE": "Inihahanda at ifa-file ang aplikasyon sa ahensyang nag-iisyu sa inyong emirate kapag na-release na ito ng isang officer.",
        "parent_BIRTH_CERTIFICATE": "Walang kailangang puntahan. Dapat handa na ang attested na marriage certificate bago magsimula ang hakbang na ito.",
        "does_MOFA_ATTESTATION": "Ifa-file ang attestation request sa MOFA pagkatapos itong i-release ng officer.",
        "parent_MOFA_ATTESTATION": "Walang kailangang puntahan.",
        "does_CONSULATE_PASSPORT": "Hindi nito maifa-file o masusubaybayan ang hakbang na ito: walang API, walang SLA at walang status feed ang konsulado. "
                                   "Tinatanong kayo ng LifeLoop sa bawat yugto at itinatala ito bilang iniulat ng magulang.",
        "parent_CONSULATE_PASSPORT": "Mag-book at pumunta sa appointment sa konsulado, saka sabihan ang LifeLoop kapag nailabas na ang passport.",
        "does_RESIDENCE_VISA": "Inaayos muli ang plano ng visa filing sa sandaling maiulat ang passport, saka ifa-file pagkatapos i-release ng officer.",
        "parent_RESIDENCE_VISA": "Walang kailangang puntahan maliban kung humingi ng dokumento ang ahensya.",
        "does_EMIRATES_ID": "Ifa-file ang aplikasyon para sa Emirates ID pagkatapos i-release ng officer at sasabihan kayo kapag oras na ng biometrics.",
        "parent_EMIRATES_ID": "Pumunta sa ICP biometrics kasama ang bata kung hihingin ito ng centre.",
        "does_INSURANCE": "Ifa-file ang dependant endorsement sa insurer sa pamamagitan ng DHA eClaimLink pagkatapos i-release ng officer.",
        "parent_INSURANCE": "Walang kailangang puntahan.",
        "sla_BIRTH_CERTIFICATE": "1-5 araw",
        "sla_MOFA_ATTESTATION": "2 oras - 3 araw ng trabaho",
        "sla_CONSULATE_PASSPORT": "Walang SLA - 2 hanggang 8 linggo, walang status feed",
        "sla_RESIDENCE_VISA": "3-10 araw, naka-hold hanggang ma-clear ang hakbang sa konsulado",
        "sla_EMIRATES_ID": "5-15 araw, ipapadala ang card sa pamamagitan ng courier",
        "sla_INSURANCE": "Target ng serbisyo ng LifeLoop (walang nailathalang SLA sa aming mga pinagkunan)",
        "fee_MOFA_ATTESTATION": "AED 150 na bayad sa attestation (Idea Canvas box H, stage 3; kumpirmahin sa kasalukuyang listahan ng bayarin ng MOFA)",
        "milestone_APPOINTMENT_BOOKED": "Naka-book na ang appointment sa konsulado",
        "milestone_APPLICATION_SUBMITTED": "Naisumite na sa konsulado ang aplikasyon para sa passport",
        "milestone_PASSPORT_ISSUED": "Nailabas na ang passport",
        "milestone_DELAYED": "Iniulat ng magulang na walang progreso sa konsulado",
        "deadline_source": "Idea Canvas box C: 120-araw na legal na deadline para sa proseso ng residence ng bagong silang",
    },
}


# The passport fields each authority receives (data minimisation), named for residents. Order matches FIELD_KEYS.
FIELD_KEYS = ("child.full_name_en", "child.full_name_ar", "child.date_of_birth", "child.sex", "child.place_of_birth",
              "child.birth_notification_ref", "father.full_name", "father.nationality", "father.emirates_id_token",
              "mother.full_name", "mother.nationality", "mother.emirates_id_token", "birth_certificate.reference",
              "child.nationality", "child.passport_present", "sponsor.emirates_id_token", "visa.reference",
              "emirates_id.reference", "sponsor.full_name")
_FIELD_NAMES: dict[str, tuple[str, ...]] = {
    "en": ("Child's name (English)", "Child's name (Arabic)", "Child's date of birth", "Child's sex", "Place of birth",
           "Hospital birth notification reference", "Father's name", "Father's nationality", "Father's Emirates ID (token)",
           "Mother's name", "Mother's nationality", "Mother's Emirates ID (token)", "Birth certificate reference",
           "Child's nationality", "Child's passport available (yes/no)", "Sponsor's Emirates ID (token)",
           "Residence visa reference", "Emirates ID application reference", "Sponsor's name"),
    "ar": ("اسم الطفل (بالإنجليزية)", "اسم الطفل (بالعربية)", "تاريخ ميلاد الطفل", "جنس الطفل", "مكان الولادة",
           "مرجع إشعار الولادة من المستشفى", "اسم الأب", "جنسية الأب", "الهوية الإماراتية للأب (رمز مشفّر)",
           "اسم الأم", "جنسية الأم", "الهوية الإماراتية للأم (رمز مشفّر)", "مرجع شهادة الميلاد",
           "جنسية الطفل", "توفّر جواز سفر الطفل (نعم/لا)", "الهوية الإماراتية للكفيل (رمز مشفّر)",
           "مرجع تأشيرة الإقامة", "مرجع طلب الهوية الإماراتية", "اسم الكفيل"),
    "hi": ("बच्चे का नाम (अंग्रेज़ी)", "बच्चे का नाम (अरबी)", "बच्चे की जन्म तिथि", "बच्चे का लिंग", "जन्म स्थान",
           "अस्पताल की जन्म सूचना का संदर्भ", "पिता का नाम", "पिता की राष्ट्रीयता", "पिता की एमिरेट्स आईडी (टोकन)",
           "माता का नाम", "माता की राष्ट्रीयता", "माता की एमिरेट्स आईडी (टोकन)", "जन्म प्रमाण पत्र का संदर्भ",
           "बच्चे की राष्ट्रीयता", "बच्चे का पासपोर्ट उपलब्ध (हाँ/नहीं)", "प्रायोजक की एमिरेट्स आईडी (टोकन)",
           "निवास वीज़ा का संदर्भ", "एमिरेट्स आईडी आवेदन का संदर्भ", "प्रायोजक का नाम"),
    "ur": ("بچے کا نام (انگریزی)", "بچے کا نام (عربی)", "بچے کی تاریخ پیدائش", "بچے کی جنس", "جائے پیدائش",
           "ہسپتال کی پیدائش کی اطلاع کا حوالہ", "والد کا نام", "والد کی قومیت", "والد کی امارات آئی ڈی (ٹوکن)",
           "والدہ کا نام", "والدہ کی قومیت", "والدہ کی امارات آئی ڈی (ٹوکن)", "پیدائش کے سرٹیفکیٹ کا حوالہ",
           "بچے کی قومیت", "بچے کا پاسپورٹ دستیاب (ہاں/نہیں)", "کفیل کی امارات آئی ڈی (ٹوکن)",
           "رہائشی ویزا کا حوالہ", "امارات آئی ڈی درخواست کا حوالہ", "کفیل کا نام"),
    "ml": ("കുട്ടിയുടെ പേര് (ഇംഗ്ലീഷ്)", "കുട്ടിയുടെ പേര് (അറബി)", "കുട്ടിയുടെ ജനനത്തീയതി", "കുട്ടിയുടെ ലിംഗം", "ജനനസ്ഥലം",
           "ആശുപത്രിയുടെ ജനന അറിയിപ്പ് റഫറൻസ്", "പിതാവിന്റെ പേര്", "പിതാവിന്റെ പൗരത്വം", "പിതാവിന്റെ എമിറേറ്റ്സ് ഐഡി (ടോക്കൺ)",
           "മാതാവിന്റെ പേര്", "മാതാവിന്റെ പൗരത്വം", "മാതാവിന്റെ എമിറേറ്റ്സ് ഐഡി (ടോക്കൺ)", "ജനന സർട്ടിഫിക്കറ്റ് റഫറൻസ്",
           "കുട്ടിയുടെ പൗരത്വം", f"കുട്ടിയുടെ {_PASSPORT_ML} ലഭ്യമാണോ (അതെ/ഇല്ല)", "സ്പോൺസറുടെ എമിറേറ്റ്സ് ഐഡി (ടോക്കൺ)",
           "റെസിഡൻസ് വിസ റഫറൻസ്", "എമിറേറ്റ്സ് ഐഡി അപേക്ഷാ റഫറൻസ്", "സ്പോൺസറുടെ പേര്"),
    "tl": ("Pangalan ng bata (Ingles)", "Pangalan ng bata (Arabic)", "Petsa ng kapanganakan ng bata", "Kasarian ng bata",
           "Lugar ng kapanganakan", "Reference ng birth notification ng ospital", "Pangalan ng ama", "Nasyonalidad ng ama",
           "Emirates ID ng ama (token)", "Pangalan ng ina", "Nasyonalidad ng ina", "Emirates ID ng ina (token)",
           "Reference ng birth certificate", "Nasyonalidad ng bata", "May passport na ang bata (oo/hindi)",
           "Emirates ID ng sponsor (token)", "Reference ng residence visa", "Reference ng aplikasyon sa Emirates ID",
           "Pangalan ng sponsor"),
}
_DISCLAIMER = {
    "en": "Uploaded documents are checked by LifeLoop officers only; each authority makes its own determination.",
    "ar": "لا يتحقق من المستندات المرفوعة إلا موظفو LifeLoop؛ وتتخذ كل جهة مختصة قرارها بنفسها.",
    "hi": "अपलोड किए गए दस्तावेज़ों की जाँच केवल LifeLoop के अधिकारी करते हैं; हर विभाग अपना फ़ैसला ख़ुद करता है।",
    "ur": "اپ لوڈ کی گئی دستاویزات کی جانچ صرف LifeLoop کے افسران کرتے ہیں؛ ہر متعلقہ ادارہ اپنا فیصلہ خود کرتا ہے۔",
    "ml": "അപ്‌ലോഡ് ചെയ്ത രേഖകൾ LifeLoop ഉദ്യോഗസ്ഥർ മാത്രമാണ് പരിശോധിക്കുന്നത്; ഓരോ വകുപ്പും സ്വന്തം തീരുമാനം എടുക്കുന്നു.",
    "tl": "Mga officer lang ng LifeLoop ang sumusuri sa mga in-upload na dokumento; ang bawat ahensya ang gumagawa ng sarili nitong pasya.",
}
# A node's status line for residents reading in another language (English keeps the authority's own wording).
STATUS_STATES = ("PENDING", "READY", "WAITING_FOR_HUMAN", "SUBMITTING", "SUBMITTED", "PROCESSING", "CLEARED", "COMPLETED",
                 "BLOCKED", "DOCUMENT_MISSING", "STALLED", "WAITING_FOR_PARENT", "REJECTED", "mock_suffix")
_STATUS_LINES: dict[str, tuple[str, ...]] = {
    "en": ("Waiting for an earlier step", "Ready - LifeLoop is preparing the filing", "Prepared - waiting for an Amer officer to release it",
           "Being filed with {entity}", "Submitted to {entity}", "{entity} is processing the application", "Cleared by {entity}",
           "Completed", "On hold - an officer is reviewing it", "Waiting for a document", "No progress yet - an officer is following up",
           "Waiting for you", "Not approved by the authority - an officer is reviewing it", " (mock)"),
    "ar": ("بانتظار خطوة سابقة", "جاهزة - يُعِدّ LifeLoop الطلب", "تم الإعداد - بانتظار أن يُجيزه موظف في Amer",
           "جارٍ تقديمه إلى {entity}", "تم تقديمه إلى {entity}", "يعالج {entity} الطلب", "أنجزه {entity}",
           "مكتملة", "متوقفة - يراجعها موظف", "بانتظار مستند", "لا تقدّم بعد - يتابعها موظف",
           "بانتظارك", "لم توافق عليها الجهة المختصة - يراجعها موظف", " (تجريبي - محاكاة)"),
    "hi": ("पिछले चरण का इंतज़ार", "तैयार - LifeLoop आवेदन तैयार कर रहा है", "तैयार - Amer के अधिकारी के रिलीज़ करने का इंतज़ार",
           "{entity} के पास दाख़िल किया जा रहा है", "{entity} को भेजा गया", "{entity} आवेदन पर काम कर रहा है", "{entity} ने क्लियर किया",
           "पूरा हुआ", "रुका हुआ - एक अधिकारी जाँच कर रहा है", "एक दस्तावेज़ का इंतज़ार", "अभी कोई प्रगति नहीं - एक अधिकारी फ़ॉलो-अप कर रहा है",
           "आपका इंतज़ार", "विभाग ने मंज़ूर नहीं किया - एक अधिकारी समीक्षा कर रहा है", " (डेमो - सिम्युलेटेड)"),
    "ur": ("پچھلے مرحلے کا انتظار ہے", "تیار - LifeLoop درخواست تیار کر رہا ہے", "تیار - Amer کے افسر کے جاری کرنے کا انتظار",
           "{entity} کے پاس جمع کرائی جا رہی ہے", "{entity} کو بھیج دی گئی", "{entity} درخواست پر کارروائی کر رہا ہے", "{entity} نے کلیئر کر دیا",
           "مکمل", "رکا ہوا - ایک افسر جائزہ لے رہا ہے", "ایک دستاویز کا انتظار", "ابھی کوئی پیش رفت نہیں - ایک افسر پیروی کر رہا ہے",
           "آپ کا انتظار", "متعلقہ ادارے نے منظور نہیں کیا - ایک افسر جائزہ لے رہا ہے", " (ڈیمو - فرضی)"),
    "ml": ("മുമ്പത്തെ ഘട്ടത്തിനായി കാത്തിരിക്കുന്നു", "തയ്യാറാണ് - LifeLoop അപേക്ഷ തയ്യാറാക്കുന്നു",
           "തയ്യാറാക്കി - ഒരു Amer ഉദ്യോഗസ്ഥൻ റിലീസ് ചെയ്യാൻ കാത്തിരിക്കുന്നു", "ഫയൽ ചെയ്യുന്നു: {entity}", "സമർപ്പിച്ചു: {entity}",
           "പരിശോധിക്കുന്നു: {entity}", "ക്ലിയർ ചെയ്തു: {entity}", "പൂർത്തിയായി", "തടഞ്ഞിരിക്കുന്നു - ഒരു ഉദ്യോഗസ്ഥൻ പരിശോധിക്കുന്നു",
           "ഒരു രേഖയ്ക്കായി കാത്തിരിക്കുന്നു", "ഇതുവരെ പുരോഗതിയില്ല - ഒരു ഉദ്യോഗസ്ഥൻ പിന്തുടരുന്നു", "നിങ്ങൾക്കായി കാത്തിരിക്കുന്നു",
           "വകുപ്പ് അംഗീകരിച്ചില്ല - ഒരു ഉദ്യോഗസ്ഥൻ പരിശോധിക്കുന്നു", " (ഡെമോ - സിമുലേറ്റഡ്)"),
    "tl": ("Naghihintay sa naunang hakbang", "Handa na - inihahanda ng LifeLoop ang filing", "Nakahanda na - naghihintay na i-release ng isang Amer officer",
           "Ifina-file sa {entity}", "Naisumite na sa {entity}", "Pinoproseso ng {entity} ang aplikasyon", "Na-clear na ng {entity}",
           "Kumpleto na", "Naka-hold - sinusuri ng isang officer", "Naghihintay ng dokumento", "Wala pang progreso - may officer na nagfa-follow up",
           "Naghihintay sa inyo", "Hindi inaprubahan ng ahensya - sinusuri ng isang officer", " (demo - simulated)"),
}
# Notification titles (bodies come from the phrasebook in app/core/i18n.py).
NOTICE_KEYS = ("notice_case_update", "notice_tried_call", "notice_calling", "notice_calls_stopped")
_NOTICES: dict[str, tuple[str, ...]] = {
    "en": ("Case update", "We tried to call", "LifeLoop is calling you", "Calls stopped"),
    "ar": ("تحديث على الملف", "حاولنا الاتصال بك", "LifeLoop يتصل بك", "تم إيقاف الاتصالات"),
    "hi": ("केस अपडेट", "हमने कॉल करने की कोशिश की", "LifeLoop आपको कॉल कर रहा है", "कॉल बंद कर दी गईं"),
    "ur": ("کیس اپ ڈیٹ", "ہم نے کال کرنے کی کوشش کی", "LifeLoop آپ کو کال کر رہا ہے", "کالز بند کر دی گئیں"),
    "ml": ("കേസ് അപ്ഡേറ്റ്", "ഞങ്ങൾ വിളിക്കാൻ ശ്രമിച്ചു", "LifeLoop നിങ്ങളെ വിളിക്കുന്നു", "കോളുകൾ നിർത്തി"),
    "tl": ("Update sa case", "Sinubukan namin kayong tawagan", "Tumatawag sa inyo ang LifeLoop", "Itinigil na ang mga tawag"),
}
for _lang, _names in _FIELD_NAMES.items():
    _table = EN if _lang == "en" else TRANSLATIONS[_lang]
    _table.update(dict(zip(NOTICE_KEYS, _NOTICES[_lang], strict=True)))
    _table.update({f"field_{k}": v for k, v in zip(FIELD_KEYS, _names, strict=True)})
    _table.update({f"status_{k}": v for k, v in zip(STATUS_STATES, _STATUS_LINES[_lang], strict=True)})
    _table["docs_disclaimer"] = _DISCLAIMER[_lang]


def step_text(key: str, lang: str | None, **params: object) -> str | None:
    """Resident-facing step text in `lang`, falling back to English; None when the key has no English source."""
    lang = normalise_lang(lang)
    template = TRANSLATIONS.get(lang, {}).get(key) or EN.get(key)
    if template is None:
        return None
    return template.format(**params) if params else template
