"""Shared enumerations for the domain model."""
from enum import Enum


class UserRole(str, Enum):
    RESIDENT = "RESIDENT"
    OPERATOR = "OPERATOR"
    GOVERNMENT_ENTITY = "GOVERNMENT_ENTITY"
    ADMIN = "ADMIN"


class CaseStatus(str, Enum):
    PENDING_CONSENT = "PENDING_CONSENT"
    IN_PROGRESS = "IN_PROGRESS"
    PAUSED = "PAUSED"
    ESCALATED = "ESCALATED"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TaskStatus(str, Enum):
    PENDING = "PENDING"
    READY = "READY"
    SUBMITTED = "SUBMITTED"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    WAITING_FOR_RESIDENT = "WAITING_FOR_RESIDENT"
    WAITING_FOR_ENTITY = "WAITING_FOR_ENTITY"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ActorType(str, Enum):
    SYSTEM = "SYSTEM"
    AI_AGENT = "AI_AGENT"
    RESIDENT = "RESIDENT"
    GOVERNMENT_ENTITY = "GOVERNMENT_ENTITY"
    ADMIN = "ADMIN"


class DomainEventType(str, Enum):
    LIFE_EVENT_CREATED = "LIFE_EVENT_CREATED"
    CONSENT_CAPTURED = "CONSENT_CAPTURED"
    TASK_CREATED = "TASK_CREATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_PROCESSING = "TASK_PROCESSING"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_DELAYED = "TASK_DELAYED"
    TASK_REJECTED = "TASK_REJECTED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RESUMED = "TASK_RESUMED"
    TASK_CANCELLED = "TASK_CANCELLED"
    DOCUMENT_REQUIRED = "DOCUMENT_REQUIRED"
    DOCUMENT_RECEIVED = "DOCUMENT_RECEIVED"
    DEPENDENCY_RESOLVED = "DEPENDENCY_RESOLVED"
    DEPENDENCY_BLOCKED = "DEPENDENCY_BLOCKED"
    WORKFLOW_REPLANNED = "WORKFLOW_REPLANNED"
    CALLBACK_REQUIRED = "CALLBACK_REQUIRED"
    CALLBACK_COMPLETED = "CALLBACK_COMPLETED"
    CASE_PAUSED = "CASE_PAUSED"
    CASE_RESUMED = "CASE_RESUMED"
    CASE_ESCALATED = "CASE_ESCALATED"
    CASE_COMPLETED = "CASE_COMPLETED"
    RESIDENT_DEFERRED = "RESIDENT_DEFERRED"


class ConsentType(str, Enum):
    CALLBACK_CONSENT = "CALLBACK_CONSENT"
    SERVICE_INITIATION_CONSENT = "SERVICE_INITIATION_CONSENT"
    DATA_PROCESSING_CONSENT = "DATA_PROCESSING_CONSENT"


class ConsentStatus(str, Enum):
    GRANTED = "GRANTED"
    DECLINED = "DECLINED"
    REVOKED = "REVOKED"


class DocumentStatus(str, Enum):
    REQUESTED = "REQUESTED"
    RECEIVED = "RECEIVED"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"


class VerificationStatus(str, Enum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"


class CallbackStatus(str, Enum):
    SCHEDULED = "SCHEDULED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


class ConversationChannel(str, Enum):
    VOICE_INBOUND = "VOICE_INBOUND"
    VOICE_OUTBOUND = "VOICE_OUTBOUND"
    DEMO = "DEMO"
    WEB = "WEB"


class ConversationStatus(str, Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


# Task-state groupings used by summaries, dashboards and notification policy.
TERMINAL_TASK_STATES = {TaskStatus.COMPLETED, TaskStatus.CANCELLED}
AUTHORITY_ACTIVE_STATES = {
    TaskStatus.SUBMITTED,
    TaskStatus.PROCESSING,
    TaskStatus.WAITING_FOR_ENTITY,
}
ACTIVE_CASE_STATES = {CaseStatus.PENDING_CONSENT, CaseStatus.IN_PROGRESS, CaseStatus.PAUSED, CaseStatus.ESCALATED}
