"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 23:55:47.006322
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.base
from alembic import op

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_entities',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('avg_processing_hours', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_government_entities')),
    sa.UniqueConstraint('slug', name=op.f('uq_government_entities_slug'))
    )
    with op.batch_alter_table('government_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_government_entities_code'), ['code'], unique=True)

    op.create_table('life_events',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('case_title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('is_configured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_events'))
    )
    with op.batch_alter_table('life_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_events_code'), ['code'], unique=True)

    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_tokens_jti'), ['jti'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RESIDENT', 'OPERATOR', 'GOVERNMENT_ENTITY', 'ADMIN', name='userrole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('workflows',
    sa.Column('life_event_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['life_event_id'], ['life_events.id'], name=op.f('fk_workflows_life_event_id_life_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflows')),
    sa.UniqueConstraint('code', name=op.f('uq_workflows_code'))
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_life_event_id'), ['life_event_id'], unique=False)

    op.create_table('life_event_cases',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('life_event_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_CONSENT', 'IN_PROGRESS', 'PAUSED', 'ESCALATED', 'COMPLETED', 'CANCELLED', name='casestatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('participants', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('memory', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['life_event_id'], ['life_events.id'], name=op.f('fk_life_event_cases_life_event_id_life_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_life_event_cases_user_id_users')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_life_event_cases_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_event_cases')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_life_event_cases_idempotency_key'))
    )
    with op.batch_alter_table('life_event_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_life_event_cases_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_event_cases_life_event_id'), ['life_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_event_cases_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_life_event_cases_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_life_event_cases_user_id'), ['user_id'], unique=False)

    op.create_table('workflow_nodes',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('service_code', sa.String(length=64), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['government_entities.id'], name=op.f('fk_workflow_nodes_entity_id_government_entities')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_nodes_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_nodes')),
    sa.UniqueConstraint('workflow_id', 'key', name=op.f('uq_workflow_nodes_workflow_id'))
    )
    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_nodes_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_nodes_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('callbacks',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SKIPPED', 'CANCELLED', name='callbackstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('trigger_event_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_for', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_call_id', sa.String(length=120), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_callbacks_case_id_life_event_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callbacks')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_callbacks_idempotency_key'))
    )
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_callbacks_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_callbacks_scheduled_for'), ['scheduled_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_callbacks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_callbacks_trigger_event_type'), ['trigger_event_type'], unique=False)

    op.create_table('consents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('CALLBACK_CONSENT', 'SERVICE_INITIATION_CONSENT', 'DATA_PROCESSING_CONSENT', name='consenttype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'DECLINED', 'REVOKED', name='consentstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('captured_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_consents_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_consent_type'), ['consent_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_consents_user_id'), ['user_id'], unique=False)

    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('callback_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('VOICE_INBOUND', 'VOICE_OUTBOUND', 'DEMO', 'WEB', name='conversationchannel', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'FAILED', name='conversationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_conversation_id', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('transcript', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_conversations_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_provider_conversation_id'), ['provider_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_user_id'), ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AI_AGENT', 'RESIDENT', 'GOVERNMENT_ENTITY', 'ADMIN', name='actortype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('old_state', sa.String(length=40), nullable=True),
    sa.Column('new_state', sa.String(length=40), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_events_case_id_life_event_cases')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_events_idempotency_key'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_processed'), ['processed'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_task_id'), ['task_id'], unique=False)

    op.create_table('service_tasks',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=True),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('service_code', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'READY', 'SUBMITTED', 'PROCESSING', 'COMPLETED', 'BLOCKED', 'WAITING_FOR_RESIDENT', 'WAITING_FOR_ENTITY', 'REJECTED', 'FAILED', 'CANCELLED', name='taskstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('replanned', sa.Boolean(), nullable=False),
    sa.Column('required_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('resident_action', sa.Text(), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_service_tasks_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['entity_id'], ['government_entities.id'], name=op.f('fk_service_tasks_entity_id_government_entities')),
    sa.ForeignKeyConstraint(['node_id'], ['workflow_nodes.id'], name=op.f('fk_service_tasks_node_id_workflow_nodes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_tasks')),
    sa.UniqueConstraint('case_id', 'key', name=op.f('uq_service_tasks_case_id')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_service_tasks_idempotency_key'))
    )
    with op.batch_alter_table('service_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_tasks_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tasks_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tasks_external_ref'), ['external_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_tasks_status'), ['status'], unique=False)

    op.create_table('workflow_edges',
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('from_node_id <> to_node_id', name='no_self_edge'),
    sa.ForeignKeyConstraint(['from_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_from_node_id_workflow_nodes')),
    sa.ForeignKeyConstraint(['to_node_id'], ['workflow_nodes.id'], name=op.f('fk_workflow_edges_to_node_id_workflow_nodes')),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], name=op.f('fk_workflow_edges_workflow_id_workflows')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_edges')),
    sa.UniqueConstraint('from_node_id', 'to_node_id', name=op.f('uq_workflow_edges_from_node_id'))
    )
    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_edges_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('documents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('doc_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'RECEIVED', 'ACCEPTED', 'REJECTED', name='documentstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('verification_status', sa.Enum('NOT_APPLICABLE', 'PENDING', 'VERIFIED', 'FAILED', name='verificationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('requested_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_documents_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], name=op.f('fk_documents_task_id_service_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_task_id'), ['task_id'], unique=False)

    op.create_table('mock_applications',
    sa.Column('entity_code', sa.String(length=64), nullable=False),
    sa.Column('service_code', sa.String(length=64), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('case_reference', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('applicant', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('required_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], name=op.f('fk_mock_applications_task_id_service_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mock_applications')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_mock_applications_idempotency_key'))
    )
    with op.batch_alter_table('mock_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_applications_case_reference'), ['case_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_applications_entity_code'), ['entity_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_applications_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_mock_applications_status'), ['status'], unique=False)

    op.create_table('task_dependencies',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_task_dependencies_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['depends_on_id'], ['service_tasks.id'], name=op.f('fk_task_dependencies_depends_on_id_service_tasks')),
    sa.ForeignKeyConstraint(['task_id'], ['service_tasks.id'], name=op.f('fk_task_dependencies_task_id_service_tasks')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('task_id', 'depends_on_id', name=op.f('uq_task_dependencies_task_id'))
    )
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_dependencies_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_depends_on_id'), ['depends_on_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_dependencies_task_id'), ['task_id'], unique=False)

    op.create_table('timeline_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AI_AGENT', 'RESIDENT', 'GOVERNMENT_ENTITY', 'ADMIN', name='actortype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('occurred_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['life_event_cases.id'], name=op.f('fk_timeline_events_case_id_life_event_cases')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_timeline_events_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_occurred_at'), ['occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_case_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('task_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_dependencies_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_depends_on_id'))
        batch_op.drop_index(batch_op.f('ix_task_dependencies_case_id'))

    op.drop_table('task_dependencies')
    with op.batch_alter_table('mock_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_applications_status'))
        batch_op.drop_index(batch_op.f('ix_mock_applications_reference'))
        batch_op.drop_index(batch_op.f('ix_mock_applications_entity_code'))
        batch_op.drop_index(batch_op.f('ix_mock_applications_case_reference'))

    op.drop_table('mock_applications')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_task_id'))
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_case_id'))

    op.drop_table('documents')
    with op.batch_alter_table('workflow_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_edges_workflow_id'))

    op.drop_table('workflow_edges')
    with op.batch_alter_table('service_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_service_tasks_external_ref'))
        batch_op.drop_index(batch_op.f('ix_service_tasks_entity_id'))
        batch_op.drop_index(batch_op.f('ix_service_tasks_case_id'))

    op.drop_table('service_tasks')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_events_processed'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_case_id'))

    op.drop_table('events')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_user_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_provider_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_case_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_consents_status'))
        batch_op.drop_index(batch_op.f('ix_consents_consent_type'))
        batch_op.drop_index(batch_op.f('ix_consents_case_id'))

    op.drop_table('consents')
    with op.batch_alter_table('callbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_callbacks_trigger_event_type'))
        batch_op.drop_index(batch_op.f('ix_callbacks_status'))
        batch_op.drop_index(batch_op.f('ix_callbacks_scheduled_for'))
        batch_op.drop_index(batch_op.f('ix_callbacks_case_id'))

    op.drop_table('callbacks')
    with op.batch_alter_table('workflow_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_nodes_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_nodes_entity_id'))

    op.drop_table('workflow_nodes')
    with op.batch_alter_table('life_event_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_event_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_life_event_cases_status'))
        batch_op.drop_index(batch_op.f('ix_life_event_cases_reference'))
        batch_op.drop_index(batch_op.f('ix_life_event_cases_life_event_id'))
        batch_op.drop_index(batch_op.f('ix_life_event_cases_event_type'))

    op.drop_table('life_event_cases')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_life_event_id'))

    op.drop_table('workflows')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_phone'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('revoked_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_tokens_jti'))

    op.drop_table('revoked_tokens')
    with op.batch_alter_table('life_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_life_events_code'))

    op.drop_table('life_events')
    with op.batch_alter_table('government_entities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_government_entities_code'))

    op.drop_table('government_entities')
    # ### end Alembic commands ###
