"""LifeLoop UAE schema: replaces the generic life-event prototype tables with the post-birth case model.

Upgrade drops the 0001 prototype tables (generic workflows/tasks) and creates the 28 LifeLoop tables:
users, organizations, auth_tokens, revoked_tokens, cases, parents, children, documents, consents, opt_outs,
life_event_nodes, life_event_edges, case_events, entity_requests, entity_statuses, callbacks, call_sessions,
transcripts, agent_sessions, approvals, officer_reviews, escalations, verification_attempts, audit_logs,
notifications, integration_events, outbox_events, consumer_receipts.
Downgrade restores the 0001 prototype schema (data is not preserved in either direction).

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 00:54:09.293082
"""
import importlib.util
from pathlib import Path
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
import app.db.base
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _legacy():
    """The 0001 prototype migration module (its upgrade/downgrade create/drop the legacy tables)."""
    path = Path(__file__).with_name("0001_initial_schema.py")
    spec = importlib.util.spec_from_file_location("lifeloop_legacy_0001", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def upgrade() -> None:
    _legacy().downgrade()  # remove the generic prototype tables
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_receipts',
    sa.Column('consumer', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consumer_receipts')),
    sa.UniqueConstraint('consumer', 'event_id', name=op.f('uq_consumer_receipts_consumer'))
    )
    op.create_index(op.f('ix_consumer_receipts_event_id'), 'consumer_receipts', ['event_id'], unique=False)
    op.create_table('integration_events',
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='integrationdirection', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSED', 'DUPLICATE', 'REJECTED', 'FAILED', name='integrationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('processed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_integration_events_idempotency_key'))
    )
    op.create_index(op.f('ix_integration_events_case_id'), 'integration_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_integration_events_provider'), 'integration_events', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_events_status'), 'integration_events', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.Enum('PLATFORM', 'SERVICE_CENTRE', name='organizationkind', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('emirate', sa.String(length=20), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_code'), 'organizations', ['code'], unique=True)
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens'))
    )
    op.create_index(op.f('ix_revoked_tokens_jti'), 'revoked_tokens', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('RESIDENT', 'OFFICER', 'ADMIN', name='userrole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_users_invited_by_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.Enum('EMAIL_VERIFICATION', 'PASSWORD_RESET', 'INVITATION', name='authtokenpurpose', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_auth_tokens_token_hash'))
    )
    op.create_index(op.f('ix_auth_tokens_purpose'), 'auth_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_tokens_user_id'), 'auth_tokens', ['user_id'], unique=False)
    op.create_table('cases',
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_officer_id', sa.Uuid(), nullable=True),
    sa.Column('life_event_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('INTAKE', 'ACTIVE', 'WAITING_FOR_PARENT', 'WAITING_FOR_HUMAN', 'ESCALATED', 'COMPLETED', 'CLOSED', name='casestatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('channel_mode', sa.Enum('VOICE', 'SMS_ONLY', name='channelmode', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('emirate', sa.String(length=20), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('intake_channel', sa.String(length=16), nullable=False),
    sa.Column('passport', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('re_entry_count', sa.Integer(), nullable=False),
    sa.Column('opted_out_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], name=op.f('fk_cases_assigned_officer_id_users')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_cases_organization_id_organizations')),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], name=op.f('fk_cases_resident_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_cases_idempotency_key'))
    )
    op.create_index(op.f('ix_cases_assigned_officer_id'), 'cases', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_cases_last_activity_at'), 'cases', ['last_activity_at'], unique=False)
    op.create_index(op.f('ix_cases_organization_id'), 'cases', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cases_reference'), 'cases', ['reference'], unique=True)
    op.create_index(op.f('ix_cases_resident_id'), 'cases', ['resident_id'], unique=False)
    op.create_index(op.f('ix_cases_risk'), 'cases', ['risk'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('occurred_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AI_AGENT', 'RESIDENT', 'OFFICER', 'ADMIN', 'GOVERNMENT_ENTITY', 'PROVIDER', name='actortype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('actor_label', sa.String(length=160), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('source', sa.Enum('AI_AGENT', 'GOVERNMENT_MOCK', 'PARENT_REPORTED', 'HUMAN_OFFICER', 'RESIDENT', 'SYSTEM', name='source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_audit_logs_case_id_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_case_occurred', 'audit_logs', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('call_sessions',
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('callback_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', name='calldirection', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider', sa.Enum('ELEVENLABS', 'SIMULATED', name='callprovider', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider_conversation_id', sa.String(length=80), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('state', sa.Enum('RINGING', 'ACTIVE', 'ENDED', 'TRANSFERRED', 'FAILED', name='callstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('sub_agent', sa.Enum('ROUTER', 'INTAKE', 'STATUS', 'EXCEPTION', name='subagent', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('disclosure_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=40), nullable=True),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('transferred_to_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_call_sessions_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_call_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_sessions')),
    sa.UniqueConstraint('provider_conversation_id', name=op.f('uq_call_sessions_provider_conversation_id'))
    )
    op.create_index(op.f('ix_call_sessions_case_id'), 'call_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_call_sessions_state'), 'call_sessions', ['state'], unique=False)
    op.create_index(op.f('ix_call_sessions_user_id'), 'call_sessions', ['user_id'], unique=False)
    op.create_table('callbacks',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('reasons', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trigger_event', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'DIALING', 'COMPLETED', 'NO_ANSWER', 'FAILED', 'CANCELLED', 'BLOCKED_NO_CONSENT', 'SMS_ONLY', name='callbackstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('consent_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_for', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('dialed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_callbacks_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_callbacks'))
    )
    op.create_index(op.f('ix_callbacks_case_id'), 'callbacks', ['case_id'], unique=False)
    op.create_index(op.f('ix_callbacks_scheduled_for'), 'callbacks', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_callbacks_status'), 'callbacks', ['status'], unique=False)
    op.create_table('case_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.Enum('AI_AGENT', 'GOVERNMENT_MOCK', 'PARENT_REPORTED', 'HUMAN_OFFICER', 'RESIDENT', 'SYSTEM', name='source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'AI_AGENT', 'RESIDENT', 'OFFICER', 'ADMIN', 'GOVERNMENT_ENTITY', 'PROVIDER', name='actortype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=True),
    sa.Column('resident_present', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('outbox_event_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_case_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_events'))
    )
    op.create_index('ix_case_events_case_occurred', 'case_events', ['case_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_case_events_event_type'), 'case_events', ['event_type'], unique=False)
    op.create_table('children',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('full_name_en', sa.String(length=160), nullable=False),
    sa.Column('full_name_ar', sa.String(length=160), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('place_of_birth', sa.String(length=160), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('birth_notification_ref', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_children_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_children')),
    sa.UniqueConstraint('case_id', name=op.f('uq_children_case_id'))
    )
    op.create_table('consents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('consent_type', sa.Enum('CALLBACK', 'DATA_PROCESSING', 'SERVICE_FILING', name='consenttype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('GRANTED', 'REVOKED', name='consentstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('captured_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_consents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents')),
    sa.UniqueConstraint('token', name=op.f('uq_consents_token'))
    )
    op.create_index(op.f('ix_consents_case_id'), 'consents', ['case_id'], unique=False)
    op.create_index(op.f('ix_consents_consent_type'), 'consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_index(op.f('ix_consents_user_id'), 'consents', ['user_id'], unique=False)
    op.create_table('documents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('category', sa.Enum('PARENT', 'CHILD', 'MARRIAGE_CERTIFICATE', 'BIRTH_CERTIFICATE', 'PASSPORT', 'VISA', 'EMIRATES_ID', 'INSURANCE', name='documentcategory', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('REQUIRED', 'UPLOADED', 'VERIFIED', 'MISSING', 'EXPIRED', 'NOT_APPLICABLE', name='documentstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('declared_available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Enum('AI_AGENT', 'GOVERNMENT_MOCK', 'PARENT_REPORTED', 'HUMAN_OFFICER', 'RESIDENT', 'SYSTEM', name='source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('issued_by', sa.String(length=60), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('case_id', 'doc_type', name=op.f('uq_documents_case_id'))
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index(op.f('ix_documents_category'), 'documents', ['category'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('escalations',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('reason', sa.Enum('TWO_FAILED_VERIFICATIONS', 'SLA_STALL', 'CONSULATE_STALL', 'DISTRESS', 'APPROVAL_QUESTION', 'DISPUTED_RECORD', 'RESIDENT_REQUEST', 'ENTITY_REJECTION', 'OFFICER_REFERRAL', name='escalationreason', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', name='escalationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('assigned_officer_id', sa.Uuid(), nullable=True),
    sa.Column('warm_transfer', sa.Boolean(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('opened_by', sa.String(length=30), nullable=False),
    sa.Column('opened_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_officer_id'], ['users.id'], name=op.f('fk_escalations_assigned_officer_id_users')),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_escalations_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escalations'))
    )
    op.create_index(op.f('ix_escalations_assigned_officer_id'), 'escalations', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_escalations_case_id'), 'escalations', ['case_id'], unique=False)
    op.create_index(op.f('ix_escalations_reason'), 'escalations', ['reason'], unique=False)
    op.create_index(op.f('ix_escalations_status'), 'escalations', ['status'], unique=False)
    op.create_table('life_event_nodes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('entity', sa.Enum('DHA', 'MOHAP', 'DOH', 'MOFA', 'CONSULATE', 'GDRFA', 'ICP', 'INSURER', name='entity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('entity_label', sa.String(length=160), nullable=False),
    sa.Column('type', sa.Enum('ENTITY_FILING', 'PARENT_REPORTED', name='nodetype', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'READY', 'SUBMITTING', 'SUBMITTED', 'PROCESSING', 'CLEARED', 'BLOCKED', 'DOCUMENT_MISSING', 'STALLED', 'WAITING_FOR_PARENT', 'WAITING_FOR_HUMAN', 'REJECTED', 'COMPLETED', name='nodestate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.String(length=240), nullable=False),
    sa.Column('status_source', sa.Enum('AI_AGENT', 'GOVERNMENT_MOCK', 'PARENT_REPORTED', 'HUMAN_OFFICER', 'RESIDENT', 'SYSTEM', name='source', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('required_documents', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('form_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('human_approval_required', sa.Boolean(), nullable=False),
    sa.Column('approval_state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstate', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('resident_present_required', sa.Boolean(), nullable=False),
    sa.Column('success_state', sa.Enum('PENDING', 'READY', 'SUBMITTING', 'SUBMITTED', 'PROCESSING', 'CLEARED', 'BLOCKED', 'DOCUMENT_MISSING', 'STALLED', 'WAITING_FOR_PARENT', 'WAITING_FOR_HUMAN', 'REJECTED', 'COMPLETED', name='successstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('sla_due_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('stalled_since', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Text(), nullable=True),
    sa.Column('next_action_owner', sa.String(length=20), nullable=True),
    sa.Column('fee_note', sa.String(length=240), nullable=True),
    sa.Column('parent_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_life_event_nodes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_event_nodes')),
    sa.UniqueConstraint('case_id', 'key', name=op.f('uq_life_event_nodes_case_id'))
    )
    op.create_index(op.f('ix_life_event_nodes_case_id'), 'life_event_nodes', ['case_id'], unique=False)
    op.create_index(op.f('ix_life_event_nodes_entity'), 'life_event_nodes', ['entity'], unique=False)
    op.create_index(op.f('ix_life_event_nodes_state'), 'life_event_nodes', ['state'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.Enum('IN_APP', 'SMS', 'EMAIL', 'VOICE', name='notificationchannel', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'SENT', 'FAILED', 'READ', name='notificationstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('is_mock', sa.Boolean(), nullable=False),
    sa.Column('sent_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('read_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_notifications_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_case_id'), 'notifications', ['case_id'], unique=False)
    op.create_index(op.f('ix_notifications_channel'), 'notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('officer_reviews',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('officer_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'DOCUMENTS_REQUESTED', 'ESCALATED', 'TRANSFERRED', 'RESOLVED', 'NOTE', name='officerdecision', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_officer_reviews_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], name=op.f('fk_officer_reviews_officer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_officer_reviews'))
    )
    op.create_index(op.f('ix_officer_reviews_case_id'), 'officer_reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_officer_reviews_officer_id'), 'officer_reviews', ['officer_id'], unique=False)
    op.create_table('opt_outs',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_opt_outs_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_opt_outs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opt_outs'))
    )
    op.create_index(op.f('ix_opt_outs_active'), 'opt_outs', ['active'], unique=False)
    op.create_index(op.f('ix_opt_outs_case_id'), 'opt_outs', ['case_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=80), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('node_key', sa.String(length=40), nullable=True),
    sa.Column('actor', sa.String(length=160), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PUBLISHED', 'PROCESSED', 'FAILED', name='outboxstatus', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('published_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('processed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_outbox_events_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_outbox_events_idempotency_key'))
    )
    op.create_index(op.f('ix_outbox_events_case_id'), 'outbox_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index('ix_outbox_status_available', 'outbox_events', ['status', 'available_at'], unique=False)
    op.create_table('parents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('FATHER', 'MOTHER', 'GUARDIAN', name='parentrole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('nationality', sa.String(length=60), nullable=False),
    sa.Column('emirates_id_hash', sa.String(length=64), nullable=True),
    sa.Column('emirates_id_last4', sa.String(length=4), nullable=True),
    sa.Column('passport_present', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_parents_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parents'))
    )
    op.create_index(op.f('ix_parents_case_id'), 'parents', ['case_id'], unique=False)
    op.create_table('verification_attempts',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('method', sa.Enum('UAE_PASS', 'KNOWLEDGE_FACTS', name='verificationmethod', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('facts_checked', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('failure_reason', sa.String(length=160), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_verification_attempts_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_verification_attempts'))
    )
    op.create_index(op.f('ix_verification_attempts_call_session_id'), 'verification_attempts', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_verification_attempts_case_id'), 'verification_attempts', ['case_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('call_session_id', sa.Uuid(), nullable=True),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('graph', sa.String(length=30), nullable=False),
    sa.Column('thread_id', sa.String(length=80), nullable=False),
    sa.Column('current_node', sa.String(length=40), nullable=True),
    sa.Column('sub_agent', sa.Enum('ROUTER', 'INTAKE', 'STATUS', 'EXCEPTION', name='subagent', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trace_id', sa.String(length=40), nullable=True),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('fk_agent_sessions_call_session_id_call_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_agent_sessions_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_sessions'))
    )
    op.create_index(op.f('ix_agent_sessions_call_session_id'), 'agent_sessions', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_case_id'), 'agent_sessions', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_thread_id'), 'agent_sessions', ['thread_id'], unique=False)
    op.create_table('approvals',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='approvalstate', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('requested_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('requested_by', sa.String(length=60), nullable=False),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_approvals_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['life_event_nodes.id'], name=op.f('fk_approvals_node_id_life_event_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_case_id'), 'approvals', ['case_id'], unique=False)
    op.create_index(op.f('ix_approvals_node_id'), 'approvals', ['node_id'], unique=False)
    op.create_index(op.f('ix_approvals_state'), 'approvals', ['state'], unique=False)
    op.create_table('entity_requests',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.Enum('DHA', 'MOHAP', 'DOH', 'MOFA', 'CONSULATE', 'GDRFA', 'ICP', 'INSURER', name='entity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('request_type', sa.String(length=60), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('external_ref', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('fields_sent', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('approval_id', sa.Uuid(), nullable=True),
    sa.Column('released_by_id', sa.Uuid(), nullable=True),
    sa.Column('released_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_status_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entity_requests_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['life_event_nodes.id'], name=op.f('fk_entity_requests_node_id_life_event_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_requests')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_entity_requests_idempotency_key'))
    )
    op.create_index(op.f('ix_entity_requests_case_id'), 'entity_requests', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_requests_entity'), 'entity_requests', ['entity'], unique=False)
    op.create_index(op.f('ix_entity_requests_external_ref'), 'entity_requests', ['external_ref'], unique=False)
    op.create_index(op.f('ix_entity_requests_node_id'), 'entity_requests', ['node_id'], unique=False)
    op.create_index(op.f('ix_entity_requests_state'), 'entity_requests', ['state'], unique=False)
    op.create_table('life_event_edges',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('from_node_id', sa.Uuid(), nullable=False),
    sa.Column('to_node_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_life_event_edges_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['from_node_id'], ['life_event_nodes.id'], name=op.f('fk_life_event_edges_from_node_id_life_event_nodes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['life_event_nodes.id'], name=op.f('fk_life_event_edges_to_node_id_life_event_nodes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_life_event_edges')),
    sa.UniqueConstraint('from_node_id', 'to_node_id', name=op.f('uq_life_event_edges_from_node_id'))
    )
    op.create_index(op.f('ix_life_event_edges_case_id'), 'life_event_edges', ['case_id'], unique=False)
    op.create_index(op.f('ix_life_event_edges_from_node_id'), 'life_event_edges', ['from_node_id'], unique=False)
    op.create_index(op.f('ix_life_event_edges_to_node_id'), 'life_event_edges', ['to_node_id'], unique=False)
    op.create_table('transcripts',
    sa.Column('call_session_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('AGENT', 'RESIDENT', 'SYSTEM', 'OFFICER', name='transcriptrole', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('sub_agent', sa.Enum('ROUTER', 'INTAKE', 'STATUS', 'EXCEPTION', name='subagent', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('tool_name', sa.String(length=60), nullable=True),
    sa.Column('is_disclosure', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['call_session_id'], ['call_sessions.id'], name=op.f('fk_transcripts_call_session_id_call_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcripts')),
    sa.UniqueConstraint('call_session_id', 'seq', name=op.f('uq_transcripts_call_session_id'))
    )
    op.create_index(op.f('ix_transcripts_call_session_id'), 'transcripts', ['call_session_id'], unique=False)
    op.create_index(op.f('ix_transcripts_case_id'), 'transcripts', ['case_id'], unique=False)
    op.create_table('entity_statuses',
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('entity', sa.Enum('DHA', 'MOHAP', 'DOH', 'MOFA', 'CONSULATE', 'GDRFA', 'ICP', 'INSURER', name='entity', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entity_statuses_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['entity_requests.id'], name=op.f('fk_entity_statuses_request_id_entity_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_statuses'))
    )
    op.create_index(op.f('ix_entity_statuses_case_id'), 'entity_statuses', ['case_id'], unique=False)
    op.create_index(op.f('ix_entity_statuses_request_id'), 'entity_statuses', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_statuses_request_id'), table_name='entity_statuses')
    op.drop_index(op.f('ix_entity_statuses_case_id'), table_name='entity_statuses')
    op.drop_table('entity_statuses')
    op.drop_index(op.f('ix_transcripts_case_id'), table_name='transcripts')
    op.drop_index(op.f('ix_transcripts_call_session_id'), table_name='transcripts')
    op.drop_table('transcripts')
    op.drop_index(op.f('ix_life_event_edges_to_node_id'), table_name='life_event_edges')
    op.drop_index(op.f('ix_life_event_edges_from_node_id'), table_name='life_event_edges')
    op.drop_index(op.f('ix_life_event_edges_case_id'), table_name='life_event_edges')
    op.drop_table('life_event_edges')
    op.drop_index(op.f('ix_entity_requests_state'), table_name='entity_requests')
    op.drop_index(op.f('ix_entity_requests_node_id'), table_name='entity_requests')
    op.drop_index(op.f('ix_entity_requests_external_ref'), table_name='entity_requests')
    op.drop_index(op.f('ix_entity_requests_entity'), table_name='entity_requests')
    op.drop_index(op.f('ix_entity_requests_case_id'), table_name='entity_requests')
    op.drop_table('entity_requests')
    op.drop_index(op.f('ix_approvals_state'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_node_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_case_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_sessions_thread_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_case_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_call_session_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_verification_attempts_case_id'), table_name='verification_attempts')
    op.drop_index(op.f('ix_verification_attempts_call_session_id'), table_name='verification_attempts')
    op.drop_table('verification_attempts')
    op.drop_index(op.f('ix_parents_case_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index('ix_outbox_status_available', table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_case_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_opt_outs_case_id'), table_name='opt_outs')
    op.drop_index(op.f('ix_opt_outs_active'), table_name='opt_outs')
    op.drop_table('opt_outs')
    op.drop_index(op.f('ix_officer_reviews_officer_id'), table_name='officer_reviews')
    op.drop_index(op.f('ix_officer_reviews_case_id'), table_name='officer_reviews')
    op.drop_table('officer_reviews')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_channel'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_case_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_life_event_nodes_state'), table_name='life_event_nodes')
    op.drop_index(op.f('ix_life_event_nodes_entity'), table_name='life_event_nodes')
    op.drop_index(op.f('ix_life_event_nodes_case_id'), table_name='life_event_nodes')
    op.drop_table('life_event_nodes')
    op.drop_index(op.f('ix_escalations_status'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_reason'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_case_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_assigned_officer_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_category'), table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_consents_user_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_consent_type'), table_name='consents')
    op.drop_index(op.f('ix_consents_case_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_table('children')
    op.drop_index(op.f('ix_case_events_event_type'), table_name='case_events')
    op.drop_index('ix_case_events_case_occurred', table_name='case_events')
    op.drop_table('case_events')
    op.drop_index(op.f('ix_callbacks_status'), table_name='callbacks')
    op.drop_index(op.f('ix_callbacks_scheduled_for'), table_name='callbacks')
    op.drop_index(op.f('ix_callbacks_case_id'), table_name='callbacks')
    op.drop_table('callbacks')
    op.drop_index(op.f('ix_call_sessions_user_id'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_state'), table_name='call_sessions')
    op.drop_index(op.f('ix_call_sessions_case_id'), table_name='call_sessions')
    op.drop_table('call_sessions')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_case_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_risk'), table_name='cases')
    op.drop_index(op.f('ix_cases_resident_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_reference'), table_name='cases')
    op.drop_index(op.f('ix_cases_organization_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_last_activity_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_assigned_officer_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_auth_tokens_user_id'), table_name='auth_tokens')
    op.drop_index(op.f('ix_auth_tokens_purpose'), table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_revoked_tokens_jti'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index(op.f('ix_organizations_code'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_integration_events_status'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_provider'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_case_id'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_consumer_receipts_event_id'), table_name='consumer_receipts')
    op.drop_table('consumer_receipts')
    # ### end Alembic commands ###
    _legacy().upgrade()  # restore the generic prototype tables
